apiVersion: v1
kind: PersistentVolume
metadata:
  name: joomla-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/joomla"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joomla-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joomla
spec:
  selector:
    matchLabels:
      app: joomla
  replicas: 1
  template:
    metadata:
      labels:
        app: joomla
    spec:
      containers:
      - name: joomla
        image: joomla:3.9
        env:
        - name: JOOMLA_DB_HOST
          value: "mysql"
        - name: JOOMLA_DB_USER
          value: "joomla"
        - name: JOOMLA_DB_PASSWORD
          value: "joomlpierre"
        - name: JOOMLA_DB_NAME
          value: "joomla"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: joomla-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: joomla-persistent-storage
        persistentVolumeClaim:
          claimName: joomla-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: joomla
spec:
  selector:
    app: joomla
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

